name: ci-docker
on:
  push:
    branches:
    - homework-add-docker
jobs:
  build:
    runs-on: ubuntu-latest
   
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: > 
          --health-cmd "pg_isready -U myuser" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Install dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Wait for PostgreSQL
        run: sleep 20 

      - name: Apply database migrations
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=postgres;Username=root;Password=root"
        run: dotnet ef database update

      - name: Run tests
        run: dotnet test --configuration Release --no-build