name: PromoCodeFactory Unit Tests

on:
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      
      - name: Restore dependencies
        run: dotnet restore
        working-directory: UnitTests/src  

     
      - name: Build project
        run: dotnet build --configuration Release --no-restore
        working-directory: UnitTests/src 

    
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
        working-directory: UnitTests/src  